version: '3.8'

services:
  nginx:
    restart: always
    build:
      context: ./.nginx
    ports:
      - 80:80
    depends_on:
      - api-gateway

  rmq-broker:
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - 5672:5672
      - 15672:15672

  api-gateway:
    container_name: api-gateway
    image: api-gateway:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        SERVICE_NAME: api-gateway
    command: yarn nx serve api-gateway
    ports:
      - 4000:3000
    depends_on:
      - rmq-broker
    volumes:
      - .:/workspace
      - /workspace/node_modules

  micro-iam:
    container_name: micro-image
    image: micro-iam:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        SERVICE_NAME: micro-iam
    command: yarn nx serve micro-iam
    ports:
      - 4001:3000
    depends_on:
      - rmq-broker
    volumes:
      - .:/workspace
      - /workspace/node_modules
