version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  mongodb:
    image: mongo:latest
    ports:
      - 37017:27017
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
